server:
  port: 8091

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      payment-success: payment-success
      payment-fail: payment-fail
      orchestrator: orchestrator
