server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      product-validation-success: product-validation-success
      product-validation-fail: product-validation-fail
      orchestrator: orchestrator